10056014CREATE TABLE IF NOT EXISTS mensajes_contacto (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  nombre   VARCHAR(120) NOT NULL,
  correo   VARCHAR(120) NOT NULL,
  telefono VARCHAR(30)  DEFAULT NULL,
  asunto   VARCHAR(150) NOT NULL,
  mensaje  TEXT         NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;