CREATE TABLE IF NOT EXISTS ventas (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  folio VARCHAR(30) NOT NULL,
  total DECIMAL(10,2) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ventas_detalle (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  venta_id INT NOT NULL,
  producto_id VARCHAR(20) NOT NULL,
  cantidad INT NOT NULL,
  precio DECIMAL(10,2) NOT NULL,
  subtotal DECIMAL(10,2) NOT NULL,
  FOREIGN KEY (venta_id) REFERENCES ventas(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
